vim.g.mapleader = ' '
local opts = { noremap = true, silent = true }
local keymap = vim.keymap.set
local telescope_builtin = require('telescope.builtin')
keymap('n', '<leader>ff', telescope_builtin.find_files)
keymap('n', '<leader>fr', telescope_builtin.oldfiles)
keymap('n', '<leader>fg', telescope_builtin.live_grep)
keymap('n', '<leader>fb', telescope_builtin.buffers)
keymap('n', '<leader>fh', telescope_builtin.help_tags)
keymap('n', '<leader>fm', function() telescope_builtin.man_pages({ sections = { 'ALL' } }) end)
keymap('n', '<leader>fc', function() telescope_builtin.find_files({ cwd = vim.fn.stdpath('config') }) end)
keymap('n', '<leader>fp', ':NeovimProjectDiscover<CR>')
keymap('n', '<leader>ds', telescope_builtin.diagnostics)
keymap('n', '<leader>bd', ':bd<CR>')
keymap('n', '<leader>n', ':bn<CR>')
keymap('n', '<leader>p', ':bp<CR>')
keymap('n', '<leader>w', ':w<CR>')
keymap('n', '<leader>q', ':q<CR>')
keymap('n', '<leader>e', ':Oil<CR>')
keymap('n', '<leader>g', ':Neogit<CR>')
keymap('n', '<leader>r', ':lua vim.lsp.buf.rename()<CR>')
keymap('n', '<leader>y', '"+y')
keymap('t', '<C-h>', [[<C-\><C-n><C-w>h]], opts)
keymap('t', '<C-j>', [[<C-\><C-n><C-w>j]], opts)
keymap('t', '<C-k>', [[<C-\><C-n><C-w>k]], opts)
keymap('t', '<C-l>', [[<C-\><C-n><C-w>l]], opts)
