# ██╗  ██╗███████╗███████╗████████╗████████╗██╗███╗   ██╗ ██████╗ ███████╗██████╗
# ╚██╗██╔╝██╔════╝██╔════╝╚══██╔══╝╚══██╔══╝██║████╗  ██║██╔════╝ ██╔════╝██╔══██╗
#  ╚███╔╝ ███████╗█████╗     ██║      ██║   ██║██╔██╗ ██║██║  ███╗███████╗██║  ██║
#  ██╔██╗ ╚════██║██╔══╝     ██║      ██║   ██║██║╚██╗██║██║   ██║╚════██║██║  ██║
# ██╔╝ ██╗███████║███████╗   ██║      ██║   ██║██║ ╚████║╚██████╔╝███████║██████╔╝
# ╚═╝  ╚═╝╚══════╝╚══════╝   ╚═╝      ╚═╝   ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝╚═════╝

Xft/Antialias   1
Xft/DPI         98304
Xft/Hinting     1
Xft/HintStyle   "hintfull"
Xft/lcdfilter   "lcddefault"
Xft/RGBA        "rgb"

Net/IconThemeName "Os-Catalina-icons"
Net/ThemeName "Mojave-Dark"

Gtk/FontName "DejaVuSansM Nerd Font 12"
Gtk/CursorThemeName "capitaine-cursors-light"
