#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝

[general]
import = [ "~/.config/alacritty/gruvbox.toml" ]

[window]
opacity = 1.0
decorations = "None"

[window.padding]
x = 10
y = 0

[font]
normal = { family = "CascadiaCove NF", style = "Regular"  }
bold = { family = "CascadiaCove NF", style = "Bold"  }
italic = { family = "CascadiaCove NF", style = "Italic"  }
bold_italic = { family = "CascadiaCove NF", style = "Bold Italic"  }
size = 11.5

[font.offset]
x = 0
y = 0

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true
