# Default colors
[colors.primary]
background = '#121212'
foreground = '#c7c7c7'

# Cursor colors
[colors.cursor]
text    = '#121212'
cursor  = '#12F512'

# Normal colors
[colors.normal]
black    = '#616161'
red      = '#FF8272'
green    = '#12f512'
yellow   = '#FEFDC2'
blue     = '#A5D5FE'
magenta  = '#FF8FFD'
cyan     = '#D0D1FE'
white    = '#F1F1F1'

# Bright colors
[colors.bright]
black    = '#8E8E8E'
red      = '#FFC4BD'
green    = '#D6FCB9'
yellow   = '#FEFDD5'
blue     = '#C1E3FE'
magenta  = '#FFB1FE'
cyan     = '#E5E6FE'
white    = '#FFFEFF'
